const sampleData = {
  products: [
    {
      name: "TWICE - THIS IS FOR Album (THIS Ver.)",
      slug: "twice-this-is-for-album-this-ver",
      category: "Album",
      description: "The latest album from TWICE, THIS IS FOR, THIS version.",
      images: [
        "/images/sample-products/twice-thisisfor-1.jpg",
        "/images/sample-products/twice-thisisfor-2.jpeg",
      ],
      price: 24.99,
      groupName: "TWICE",
      company: "JYP Entertainment",
      version: "THIS Ver.",
      rating: 4.9,
      numReviews: 152,
      stock: 50,
      isFeatured: true,
      banner: "banner-twice.png",
    },
    {
      name: "TripleS - ASSEMBLE25 Album (Are You Alive Ver.)",
      slug: "triples-assemble25-album-are-you-alive-ver",
      category: "Album",
      description: "The full 24-member debut album from TripleS.",
      images: [
        "/images/sample-products/triples-assemble25-1.jpg",
        "/images/sample-products/triples-assemble25-2.jpg",
      ],
      price: 22.5,
      groupName: "TripleS",
      company: "MODHAUS",
      version: "Are You Alive Ver.",
      rating: 4.8,
      numReviews: 95,
      stock: 80,
      isFeatured: true,
      banner: "banner-triples.png",
    },
    {
      name: "SEVENTEEN - HAPPY BURSTDAY Album (Daredevil Ver.)",
      slug: "seventeen-happy-burstday-album-daredevil-ver",
      category: "Album",
      description: "Special anniversary album release from SEVENTEEN.",
      images: [
        "/images/sample-products/svt-burstday-1.jpg",
        "/images/sample-products/svt-burstday-2.jpg",
      ],
      price: 27.99,
      groupName: "SEVENTEEN",
      company: "PLEDIS Entertainment",
      version: "Daredevil Ver.",
      rating: 4.9,
      numReviews: 210,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "TripleS - Summer Edition Official Photocard (Kotone 332Z)",
      slug: "triples-summer-edition-photocard-kotone-332z",
      category: "Photocard",
      description: "Official Summer Edition objekt featuring Kotone No. 332Z.",
      images: ["/images/sample-products/pc-kotone-332z.jpg"],
      price: 8.99,
      groupName: "TripleS",
      company: "MODHAUS",
      version: "Summer Edition",
      rating: 5.0,
      numReviews: 25,
      stock: 5,
      isFeatured: false,
      banner: null,
    },
    {
      name: "TWICE - Strategy Official Photocard (Jeongyeon)",
      slug: "twice-strategy-photocard-jeongyeon",
      category: "Photocard",
      description:
        "Official photocard of Jeongyeon from TWICE's 'Strategy' album era.",
      images: ["/images/sample-products/pc-jeongyeon-strategy.jpeg"],
      price: 12.5,
      groupName: "TWICE",
      company: "JYP Entertainment",
      version: "Strategy Album",
      rating: 4.8,
      numReviews: 30,
      stock: 3,
      isFeatured: true,
      banner: null,
    },
    {
      name: "aespa - Whiplash Official Photocard (Winter)",
      slug: "aespa-whiplash-photocard-winter",
      category: "Photocard",
      description:
        "Official photocard of Winter from aespa's 'Armageddon' album, 'Whiplash' concept.",
      images: ["/images/sample-products/pc-winter-whiplash.jpg"],
      price: 15.99,
      groupName: "aespa",
      company: "SM Entertainment",
      version: "Armageddon - Whiplash Set",
      rating: 4.9,
      numReviews: 45,
      stock: 2,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
